import WithNavBar from 'layouts/WithNavBar';
import type { NextPage } from 'next';
import Head from 'next/head';

import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WithNavBar>
        <div className="flex items-center justify-center h-full flex-grow">
          <h1 className="bg-blue-500  p-3 uppercase font-bold align-middle text-3xl rounded-xl">
            generator statystyk dla zespołu rangers
          </h1>
        </div>
      </WithNavBar>
    </div>
  );
};

export default Home;
